[package]
name = "fat-macho"
version = "0.5.0"
authors = ["messense <messense@icloud.com>"]
description = "Mach-O Fat Binary Reader and Writer"
keywords = ["fat", "mach", "macho", "universal", "universal2"]
edition = "2021"
rust-version = "1.81"
readme = "README.md"
license = "MIT"
repository = "https://github.com/messense/fat-macho-rs.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-bitcode = { version = "0.4", optional = true }

[dev-dependencies]
goblin = "0.10.0"

[features]
default = ["bitcode"]
bitcode = ["llvm-bitcode"]

[[bench]]
name = "bench"
harness = false
