from os import PathLike
from typing import Optional, Union


class FatWriter:
    def __init__(self): ...
    def add(self, data: bytes): ...
    def add_file(self, path: Union[str, PathLike]): ...
    def remove(self, arch: str) -> Optional[bytes]: ...
    def exists(self, arch: str) -> bool: ...
    def write_to(self, path: Union[str, PathLike]): ...
    def generate(self) -> bytes: ...
